# Test Scenario DSL Schema
# This file documents the available actions for test scenarios

actions:
  # Navigation
  - tap: "<element>"           # Tap on button/element by text or @accessibilityId
  - back:                      # Press system back button
  - navigate: "<route>"        # Navigate to specific route

  # Input
  - type:
      field: "<label>"         # Input field label or @accessibilityId
      text: "<value>"          # Text to enter
  - clear: "<field>"           # Clear input field

  # Gestures
  - swipe: "<up|down|left|right>"
  - scroll:
      to: "<element>"          # Scroll until element visible
  - drag:
      from: "<element>"
      to: "<element>"

  # Assertions
  - see: "<text>"              # Assert text is visible
  - notSee: "<text>"           # Assert text is NOT visible
  - seeElement: "<element>"    # Assert element exists
  - notSeeElement: "<element>" # Assert element does NOT exist
  - seeCount:
      element: "<element>"
      count: <number>          # Assert exact count of elements

  # Timing
  - wait: "<duration>"         # Wait for duration (e.g., "2s", "500ms")
  - waitFor: "<element>"       # Wait for element to appear
  - waitForGone: "<element>"   # Wait for element to disappear

  # Debugging
  - screenshot: "<name>"       # Capture screenshot
  - log: "<message>"           # Log message for debugging

  # Platform-specific
  - platform:
      ios:
        - <action>             # iOS-only actions
      android:
        - <action>             # Android-only actions

# Element identifiers:
#   "Text"              - Find by visible text
#   "@accessibilityId"  - Find by accessibility ID (preferred)
#   "#testId"           - Find by testID attribute
